---
# Path where the git repo can been copied
home_dir: 

# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: "ce"
docker_version: "17.03.0~ce-0~ubuntu-xenial"
docker_package: "docker-{{ docker_edition }}={{ docker_version }}"
docker_package_state: present
docker_user: kubeuser
docker_group: docker

# Used only for Debian/Ubuntu. Switch 'stable' to 'edge' if needed.
docker_apt_release_channel: stable
docker_apt_repository: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"

# for flannel install 
pod_network_cidr: 10.244.0.0/16

# Used when configuring kubectl
kubectl_user: kubeuser
kubectl_group: kubeuser
kubectl_home: /home/kubeuser

# Kubernetes Parameters
init_token: ac7da3.b2cofcda6ab01976
kube_version: stable

