---
- name: Update apt packages
  apt:
    update_cache: yes

- name: Ensure dependencies are installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Update and Upgrade apt packages
  apt:
    update_cache: yes

- name: Add Docker apt key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: yes

- name: Install Docker.
  package: 
    name: "{{ docker_package }}" 
    state: "{{ docker_package_state }}"

- name: Ensure Docker is started and enabled at boot.
  systemd:
    name: docker
    state: started
    enabled: yes

- name: add default user to docker group
  user:
    name: "{{ docker_user }}"
    groups: "{{ docker_group }}"
    append: yes

